### ISSUE TITLE
Remove the alert status after page reload or clicking on close button.

### ISSUE THREAD

**Issue by Libbna** [Libbna/CUSTOM-CMS#115]
After login or register or creating a new menu, etc. The success alert pops up but after the page reload it still shows up which is not correct and needs to be fixed.

**Comment by Libbna** [comment]
![Screenshot from 2022-01-02 20-59-01](https://user-images.githubusercontent.com/46792570/147880728-f380118e-2327-4c3d-8833-42f8fd833345.png)

**Comment by Libbna** [comment]
c0efbd8: 
![image](https://user-images.githubusercontent.com/46792570/148102190-3f28c936-2629-4e69-8808-127d85c151cd.png)

**Comment by Libbna** [comment]
@vbadkar  @RChaubey16 
Now another issue is when we will reload the page the alert box will again shows up even after clicking on the close button, if we again reloads the page then again alert will pop up.

**Comment by vbadkar** [comment]
Parent issue #214
