### ISSUE TITLE
Create a service for message display.

### ISSUE THREAD

**Issue by Libbna** [Libbna/CUSTOM-CMS#145]
Requirement: 
Create a service for message display. For e.g. we can a create a service to provide a functionality to display messages or alerts. Like while login or register, creating new article or block, etc we can get a success message through service. 

For ref: 
https://symfony.com/doc/current/service_container.html
https://www.drupal.org/docs/drupal-apis/services-and-dependency-injection/structure-of-a-service-file

**Comment by RChaubey16** [comment]
Parent issue : #214

**Comment by RChaubey16** [comment]
Parent issue #214

**Comment by Libbna** [comment]
Also going to try php-flasher - https://php-flasher.github.io/docs/installation/
