### ISSUE TITLE
Base Url not working after the admin operation.

### ISSUE THREAD

**Issue by RChaubey16** [Libbna/CUSTOM-CMS#150]
* After performing some admin operartions, the rendered template does not seem to be appropriate. The styling also is not getting applied.
* There is some issue with the base tag refer below screenshot for more info
![Screenshot from 2022-01-05 12-39-19](https://user-images.githubusercontent.com/83503327/148180265-5325d31f-5849-47db-9a64-26315e234835.png)

**Comment by vbadkar** [comment]
This issue has been fxed in PR #151 . Hence closing this issue.
