### ISSUE TITLE
Add Search Feature to the CMS.

### ISSUE THREAD

**Issue by RChaubey16** [Libbna/CUSTOM-CMS#176]
* Add search template for displaying the results.
* Add controller and model method for the same.

**Comment by JayKandari** [comment]
Sample requirements breakdown: 
* Show the search button on header. 
* create a search results page (route)
* make sure the search form is getting submitted as a GET REQUEst.
* datasource for search results - articles/blog only. 
* search in the following fields of articles - title, body, categoryname.
* when showing search results - show following fields - title, short body description, if image is available then show a thumbnail also. show author also. 
* show pagination - 
* show categories on right sidebar... article categories.. 
* on clicking those article categories, user should be redirected to the same search results page but with the selected category.
