### ISSUE TITLE
Add service container to the CMS.

### ISSUE THREAD

**Issue by RChaubey16** [Libbna/CUSTOM-CMS#181]
* Add a service container to the CMS to inject dependency in the controller actions as and when required.
* Use the `Dependency Injection` component in Symfony.

**Comment by RChaubey16** [comment]
* Went through the Dependency Injection component of Symfony.
* https://symfony.com/doc/current/components/dependency_injection.html#:~:text=The%20DependencyInjection%20component%20implements%20a,service%20containers%20see%20Service%20Container.

**Comment by vbadkar** [comment]
Added.

**Comment by vbadkar** [comment]
Added.
