### ISSUE TITLE
Implelement psr-4 autoloading using composer

### ISSUE THREAD

**Issue by Libbna** [Libbna/CUSTOM-CMS#19]

**Comment by Libbna** [comment]
for auto-loading ref: https://www.youtube.com/watch?v=04aTM01Y3uQ&ab_channel=howCode
for routing: https://www.youtube.com/watch?v=DpbUqJcch0Y&list=RDCMUCovR8D97-8qmQ8hWQW0d3ew&index=4&ab_channel=howCode

**Comment by Libbna** [comment]
a0d1877: autoloading psr-1 standard is used.  
PSR-4 standard need to be followed. 

**What is PSR?**
-> The PHP Standard Recommendation is a PHP specification published by the PHP Framework Interop Group. 
* Files MUST use only <?php and <?= tags.
* Files MUST use only UTF-8 without BOM for PHP code.
* Files SHOULD either declare symbols (classes, functions, constants, etc.) or cause side-effects (e.g. generate output, change .ini settings, etc.) but SHOULD NOT do both.
* Namespaces and classes MUST follow an "autoloading" PSR: [PSR-0, PSR-4].
* Class names MUST be declared in StudlyCaps.
* Class constants MUST be declared in all upper case with underscore separators.
* Method names MUST be declared in camelCase.

_Ref: https://www.php-fig.org/psr/psr-1/_


**What is PSR-4 autoloader?** 
-> This PSR describes a specification for autoloading classes from file paths. It is fully interoperable, and can be used in addition to any other autoloading specification, including PSR-0. This PSR also describes where to place files that will be autoloaded according to the specification.

* The term "class" refers to classes, interfaces, traits, and other similar structures.
* A fully qualified class name has the following form:
          \<NamespaceName>(\<SubNamespaceNames>)*\<ClassName>

_Ref: https://www.php-fig.org/psr/psr-4/_

**Comment by Libbna** [comment]
Ref: https://code.tutsplus.com/tutorials/how-to-autoload-classes-with-composer-in-php--cms-35649

**Comment by RChaubey16** [comment]
Added.
