### ISSUE TITLE
Logo image should be updated on Submit. 

### ISSUE THREAD

**Issue by Libbna** [Libbna/CUSTOM-CMS#191]
- click on the config button and upload an image for logo. 
Issue facing: 
- after clicking on the submit button the updated logo will not be displayed. 
- it will only visible when you click on some other link. - Basically the main issue is, on submit the page should be reload.

**Comment by JayKandari** [comment]
SAMPLE FORMAT: 

**Requirements:** 
* abc
* pqr

**TI:** 
* def
* ghi

**Comment by vbadkar** [comment]
This issue has been fixed in PR #210 , to test this out visit #210 .
