### ISSUE TITLE
Redirect and show message after adding the logo.

### ISSUE THREAD

**Issue by omkar-pd** [Libbna/CUSTOM-CMS#198]
**Requirement:-**

-  Currently, when user adds the logo we have to refresh the page to see the changes.
-  But page should be redirected/refreshed and after that we should display message as - Logo is added.

**Comment by vbadkar** [comment]
The issue with logo appearing only after refreshing the page has been fixed in PR, Visit PR #210 to test this.
WIP for display messages.*

**Comment by Libbna** [comment]
@vbadkar  you are working on this issue?

**Comment by vbadkar** [comment]
Parent issue #214
