### ISSUE TITLE
Logged In User Name Not Show Properly On /articleForm Page

### ISSUE THREAD

**Issue by Mspiro** [Libbna/CUSTOM-CMS#200]
![image](https://user-images.githubusercontent.com/32816725/148973929-32c3c4cf-a173-453a-a7aa-c5d1bfed1169.png)
User name not visible in the articleForm page.

**Comment by vbadkar** [comment]
@Mspiro Can you add steps to reproduce this issue?

**Comment by RChaubey16** [comment]
@vbadkar are you working on this issue ??

**Comment by vbadkar** [comment]
@RChaubey16 yes
