### ISSUE TITLE
Default Logo image is not present. 

### ISSUE THREAD

**Issue by Mspiro** [Libbna/CUSTOM-CMS#203]
Here is logo.png file is not present in to the repo assets/images/logo/logo.png
![image](https://user-images.githubusercontent.com/32816725/149076698-799ec251-c357-46cf-bd3d-08910650d849.png)

![image](https://user-images.githubusercontent.com/32816725/149076889-670eb484-d210-4ad7-856f-727ab05931d9.png)

**Comment by Libbna** [comment]
@Mspiro as we have used image library to resize the image, so after the image is resized it will store in DB as 
assets/images/logo/resized_logo.png. - Image name will get changed - prefixed with resized. 

Can you check, by uploading some other image as logo and see the difference. If still you face this issue then let me know.

**Comment by Mspiro** [comment]
@Libbna Yes, but this is works only for registered user. But whenever any new user download project at that time he/she did not get any default logo. We have to add that one aslo.
