### ISSUE TITLE
Use single template hierarachy in custom CMS.

### ISSUE THREAD

**Issue by JayKandari** [Libbna/CUSTOM-CMS#25]
Currently we are rendering different twig template for each of the different route. 

We should change this to the way how Drupal does it: 

So for every route, we will be rendering a single template and that template will have capability to nest other sub templates creating a whole template hierarchy.... and based on the route, the content of those template will change and based on the requirements respective templates will change.. 

think of it as how it is done in Drupal.

**Comment by vbadkar** [comment]
Template heirararchy in Drupal 
https://www.drupal.org/node/173880
