### ISSUE TITLE
Add asteric * to required fields. 

### ISSUE THREAD

**Issue by Libbna** [Libbna/CUSTOM-CMS#254]
Requirement:
* Make the required fields identified by the user for better user experience
* Add a red asteric * which will identify the field as required.

Technical implementation:
* Add an extra class to the <div> tag which contains the required input field
* Add a ::before or ::after styling to that class 
* Give the content attribute value of "*" and give it red color

Estimated time:
* 1hr

**Comment by JayKandari** [comment]
Can we add an estimate on this ticket?

**Comment by vbadkar** [comment]
Completed.
