### ISSUE TITLE
Remove `node_module` folder from repo.

### ISSUE THREAD

**Issue by JayKandari** [Libbna/CUSTOM-CMS#259]
The `node_modules` folder should not be a part of the repository. This folder is dynamically generated when we do `npm install`. 
So as a part of this ticket do the following: 

* Remove the folder `node_modules`.
* Add this `node_modules` to `.gitignore` file.
* Modify the documentation where project setup is done. Add a line when to perform `npm install` and also mention which node version to use for it to work correctly.

**Comment by vbadkar** [comment]
Folder deleted.
