### ISSUE TITLE
Fix all the coding standard issues. 

### ISSUE THREAD

**Issue by Libbna** [Libbna/CUSTOM-CMS#263]
- to check the coding standard issues in your project, make sure these libraries are installed. 
- PHP code sniffer, drupal/coder, dealerdirect/phpcodesniffer-composer-installer, php pre-cmmit hook.
- after running the `git commit` command the terminal will show the errors and warnings related to coding. 
- committing changes will not be possible if the errors are present, resolve the error and then commit the changes. 
- if there are no coding standard issues in your file or folder then the changes will be committed successfully.

**Comment by Mspiro** [comment]
Pre-commit hook installed successfully.
