### ISSUE TITLE
Delete unnecessary files from the repo

### ISSUE THREAD

**Issue by vbadkar** [Libbna/CUSTOM-CMS#277]
### Requirement

- Repositiory contains some unnecessary files such as route.php, contactForm.html.twig, etc. which are not required anymore, delete those files from the repo.

Estimation - 10mins

**Comment by JayKandari** [comment]
@vbadkar : can you mention all the files which are not required?

**Comment by vbadkar** [comment]
Files not required are as follows:
* route.php
* contact.html.twig
* contactForm.html.twig
* home.php
