### ISSUE TITLE
Fix the height of banner arrows. 

### ISSUE THREAD

**Issue by Mspiro** [Libbna/CUSTOM-CMS#278]
**Requirement:**
- Height of the banner button need to reduce. 

![image](https://user-images.githubusercontent.com/32816725/153588636-b7cc8715-c1b0-4531-8a1b-143d7e282b02.png)

**Technical Implementation:**
- Reduce size of arrow button on home page banner.

**Comment by JayKandari** [comment]
Can we add an estimate before we start our work?
