### ISSUE TITLE
Implementing Scroll to top feature.

### ISSUE THREAD

**Issue by AkshayDalvi15** [Libbna/CUSTOM-CMS#291]
**Requirement:**
* To implement a floating button on the right bottom side which will scroll to the top of the website.

**Technical Implementation:**
* When we scroll down, a floating button with an upwards arrow inside the button will appear on the bottom right side.
* When we scroll down, the display setting the button will switch to block from none and will appear.
* When we click on the floating button it will automatically scroll us to the top of the website.
* We set the document.body.scrollTop to zero which will scroll to the top of the website.

**Comment by RChaubey16** [comment]
@AkshayDalvi15 already working on this.
