### ISSUE TITLE
Solve the issue related to route paths.

### ISSUE THREAD

**Issue by RChaubey16** [Libbna/CUSTOM-CMS#33]
* Currently, the path in routes are written in this manner "/custom_cms/home" which is incorrect.
* Instead, the routing should be "/home", very straightforward.
* Need to convert all the "/custom_cms/home" routes to "/home" and similarly rest of the routes as well.

**Comment by vbadkar** [comment]
@RChaubey16 @Libbna , I have fixed the route issue, can you verify and close this issue

**Comment by RChaubey16** [comment]
Issue resolved.
