### ISSUE TITLE
Implement symphony autoloading 

### ISSUE THREAD

**Issue by Libbna** [Libbna/CUSTOM-CMS#35]

**Comment by Libbna** [comment]
After clicking on the home link, it redirects to error page. 
![Screenshot from 2021-12-13 20-06-32](https://user-images.githubusercontent.com/46792570/145831691-6ae182af-4cf8-4a4a-894e-e45d432ccb11.png)

Doing some RnD on this issue.

**Comment by RChaubey16** [comment]
Done
