### ISSUE TITLE
Add PHP code sniffer to the CMS.

### ISSUE THREAD

**Issue by RChaubey16** [Libbna/CUSTOM-CMS#84]
**Completed:**
* PHP code sniffer is a tool to check any coding standards that needs improvement. 
TO setup the PHP code sniffer in your project, follow the steps mentioned in the below github link. 
https://github.com/squizlabs/PHP_CodeSniffer/issues

**Pending :**

* Install following Drupal Coding Standards - Drupal & DrupalPractice. See: https://www.drupal.org/project/coder
* Install a git commit hook - Add a manual step which can be added to our local - that checks phpcode sniffer for changed files only. This is required because - if the code sniffer fails git commit hook will not allow to commit before coding standards are fixed.

**Comment by Libbna** [comment]
Run these two commands to check the coding standards of your file or folder. 

phpcs dir_name/file_name
phpcbf dir_name/file_name

**Comment by JayKandari** [comment]
Reopening this issue due to following changes. 

**Pending items:** 

* Install following Drupal Coding Standards - `Drupal` & `DrupalPractice`.  See: https://www.drupal.org/project/coder
* Install a `git commit` hook - Add a manual step which can be added to our local - that checks phpcode sniffer for changed files only. This is required because - if the code sniffer fails git commit hook will not allow to commit before coding standards are fixed. 


Feel free to divide these tasks as sub-issues.

**Comment by JayKandari** [comment]
To install `Drupal` & `DrupalPractice` standards to PHP_CodeSniffer library perform following steps: 
**Installation:** 
* Install PHP_Codesniffer library globally (or in a project - remove the keyword `global`) -> `composer global require squizlabs/php_codesniffer`.
* Install Drupal coder standards to composer global package (if you have installed PHP_CodeSniffer locallly on a project then add this package locally) -> `composer global require drupal/coder`
* Install the `dealerdirect/phpcodesniffer-composer-installer` composer plugin which automatically detects the standards: `composer global require dealerdirect/phpcodesniffer-composer-installer`

**More info:**
* View which all standards are available in your phpcs installation : `phpcs -i`. 
* See all commands in phpcs: `phpcs --help`

**Run phpcs:**
* check single standard: `phpcs --standard=Drupal path/to/filename.php`
* Check multiple standards: `phpcs --standard=Drupal,DrupalPractice path/to/filename.php second/file.php`
* and so on. 

For more detailed information: See this [documentation](https://www.drupal.org/docs/contributed-modules/code-review-module/installing-coder-sniffer) on drupal.org

**Comment by vbadkar** [comment]
Code sniffer added.
